use num_enum::{IntoPrimitive, TryFromPrimitive};

#[allow(clippy::type_complexity)]
pub enum SdoRequest {
    SerialNumber,
    SoftwareVersion,
    HardwareVersion,
    DeviceErrorHistory,
    CellVoltages,
    DeviceConfigInfo,
    DeviceSerialNumberInfo,
    DeviceDateInfo,
    DeviceVariantInfo,
    DeviceControlParam,
    DeviceOperationTime,
    DeviceErrorCounter,
    CellVoltageMinMax,
    CellVoltageLimit,
    BatteryVoltage,
    BatteryVoltageLimit,
    BatteryCurrent,
    BatteryCurrentLimit,
    FetTemperature,
    FetTemperatureMinMax,
    FetTemperatureLimit,
    CellTemperature,
    CellTemperatureMinMax,
    CellTemperatureLimit,
    CellBalanceStatus,
    CellBalanceLimit,
    CellImpedance,
    BatteryCapacity,
    BatteryCapacityParam,
    BatteryCycleCount,
    BatteryChargeVoltage,
    BatteryChargeCurrent,
    BatteryChargeTemperature,
    MasterBatteryTemperature,
}

#[allow(clippy::type_complexity)]
pub enum SdoResponse {
    SerialNumber {
        node_id: u8,
        value: Result<u16, String>,
    },
    SoftwareVersion {
        node_id: u8,
        value: Result<String, String>,
    },
    HardwareVersion {
        node_id: u8,
        value: Result<String, String>,
    },
    DeviceErrorHistory {
        node_id: u8,
        value: Result<Vec<DeviceError>, String>,
    },
    CellVoltages {
        node_id: u8,
        value: Result<Vec<f32>, String>,
    },
    DeviceConfigInfo {
        node_id: u8,
        value: Result<(String, String, String), String>,
    },
    DeviceSerialNumberInfo {
        node_id: u8,
        value: Result<(u32, u32, u32), String>,
    },
    DeviceDateInfo {
        node_id: u8,
        value: Result<(u16, u16, u16), String>,
    },
    DeviceVariantInfo {
        node_id: u8,
        value: Result<(u8, u8, u8, u16, u16, u16, u8), String>,
    },
    DeviceControlParam {
        node_id: u8,
        value: Result<u16, String>,
    },
    DeviceOperationTime {
        node_id: u8,
        value: Result<(u8, u8, u8, u8, u8, u32, u32, u32, u32, u32), String>,
    },
    DeviceErrorCounter {
        node_id: u8,
        value: Result<Vec<u16>, String>,
    },
    CellVoltageMinMax {
        node_id: u8,
        value: Result<(u32, u32), String>,
    },
    CellVoltageLimit {
        node_id: u8,
        value: Result<u32, String>,
    },
    BatteryVoltage {
        node_id: u8,
        value: Result<(u32, u32, u32), String>,
    },
    BatteryVoltageLimit {
        node_id: u8,
        value: Result<u32, String>,
    },
    BatteryCurrent {
        node_id: u8,
        value: Result<(i32, i32, i32, i32, i32), String>,
    },
    BatteryCurrentLimit {
        node_id: u8,
        value: Result<i32, String>,
    },
    FetTemperature {
        node_id: u8,
        value: Result<(i32, i32), String>,
    },
    FetTemperatureMinMax {
        node_id: u8,
        value: Result<(i32, i32), String>,
    },
    FetTemperatureLimit {
        node_id: u8,
        value: Result<i32, String>,
    },
    CellTemperature {
        node_id: u8,
        value: Result<(i32, i32, i32, i32, i32, i32), String>,
    },
    CellTemperatureMinMax {
        node_id: u8,
        value: Result<(i32, i32), String>,
    },
    CellTemperatureLimit {
        node_id: u8,
        value: Result<i32, String>,
    },
    CellBalanceStatus {
        node_id: u8,
        value: Result<(u16, u16, u16), String>,
    },
    CellBalanceLimit {
        node_id: u8,
        value: Result<u32, String>,
    },
    CellImpedance {
        node_id: u8,
        value: Result<[u16; 18], String>,
    },
    BatteryCapacity {
        node_id: u8,
        value: Result<(u32, u32, u32, u8, u8, u32, u32), String>,
    },
    BatteryCapacityParam {
        node_id: u8,
        value: Result<u8, String>,
    },
    BatteryCycleCount {
        node_id: u8,
        value: Result<(u32, u32, u32, u32, u32, u32, u32, u32, u32), String>,
    },
    BatteryChargeVoltage {
        node_id: u8,
        value: Result<(u32, u32, u32), String>,
    },
    BatteryChargeCurrent {
        node_id: u8,
        value: Result<(u32, u32, u32, u32, u32, u16, u16, u16, u16, u32), String>,
    },
    BatteryChargeTemperature {
        node_id: u8,
        value: Result<(i32, i32, i32, i32, i32, i32), String>,
    },
    MasterBatteryTemperature {
        node_id: u8,
        value: Result<(i32, i32), String>,
    },
}

#[derive(Debug, Clone, Default)]
pub struct MasterInfo {
    pub voltage: Option<f32>,
    pub current: Option<f32>,
    pub soc: Option<f32>,
    pub charge_voltage_request: Option<f32>,
    pub charge_current_request: Option<f32>,
    pub battery_status: Option<u8>,
    pub max_battery_fet_temp: Option<f32>,
    pub max_battery_cell_temp: Option<f32>,
    pub master_design_capacity: Option<f32>,
    pub master_full_charge_capacity: Option<f32>,
    pub master_remaining_capacity: Option<f32>,
    pub last_seen: Option<std::time::SystemTime>,
}

#[derive(Debug)]
#[allow(clippy::type_complexity)]
pub struct VartaEasyblade {
    pub node_id: u8,
    pub serial_number: Option<u16>,
    pub software_version: Option<String>,
    pub hardware_version: Option<String>,
    pub last_seen: std::time::SystemTime,
    pub voltage: Option<f32>,
    pub current: Option<f32>,
    pub soc: Option<f32>,
    pub soh: Option<f32>,
    pub cell_voltages: Option<Vec<f32>>,
    pub device_errors: Option<Vec<DeviceError>>,
    pub fet_status: Option<(bool, bool, bool)>,
    pub device_config_info: Option<(String, String, String)>,
    pub device_serial_number_info: Option<(u32, u32, u32)>,
    pub device_date_info: Option<(u16, u16, u16)>,
    pub device_variant_info: Option<(u8, u8, u8, u16, u16, u16, u8)>,
    pub device_control_param: Option<u16>,
    pub device_operation_time: Option<(u8, u8, u8, u8, u8, u32, u32, u32, u32, u32)>,
    pub device_error_counter: Option<Vec<u16>>,
    pub cell_voltage_min_max: Option<(u32, u32)>,
    pub cell_voltage_limit: Option<u32>,
    pub battery_voltage: Option<(u32, u32, u32)>,
    pub battery_voltage_limit: Option<u32>,
    pub battery_current: Option<(i32, i32, i32, i32, i32)>,
    pub battery_current_limit: Option<i32>,
    pub fet_temperature: Option<(i32, i32)>,
    pub fet_temperature_min_max: Option<(i32, i32)>,
    pub fet_temperature_limit: Option<i32>,
    pub cell_temperature: Option<(i32, i32, i32, i32, i32, i32)>,
    pub cell_temperature_min_max: Option<(i32, i32)>,
    pub cell_temperature_limit: Option<i32>,
    pub cell_balance_status: Option<(u16, u16, u16)>,
    pub cell_balance_limit: Option<u32>,
    pub cell_impedance: Option<[u16; 18]>,
    pub battery_capacity: Option<(u32, u32, u32, u8, u8, u32, u32)>,
    pub battery_capacity_param: Option<u8>,
    pub battery_cycle_count: Option<(u32, u32, u32, u32, u32, u32, u32, u32, u32)>,
    pub battery_charge_voltage: Option<(u32, u32, u32)>,
    pub battery_charge_current: Option<(u32, u32, u32, u32, u32, u16, u16, u16, u16, u32)>,
    pub battery_charge_temperature: Option<(i32, i32, i32, i32, i32, i32)>,
    pub master_battery_temperature: Option<(i32, i32)>,
    pub sdo_request_tx: tokio::sync::mpsc::UnboundedSender<SdoRequest>,
    pub task_handle: tokio::task::JoinHandle<()>,
    pub cancellation_token: tokio_util::sync::CancellationToken,
}

/// Device Error values logged by the Varta Easyblade module in SDO 0x2018
/// (DeviceError History Values).
#[repr(u8)]
#[derive(Debug, PartialEq, IntoPrimitive, TryFromPrimitive)]
pub enum DeviceError {
    None = 0x00,

    CellOverTempWhileCharging = 0x01,
    CellUnderTempWhileCharging = 0x02,
    ChargeFetOverTempWhileCharging = 0x03,
    CellOverTempWhileDischarging = 0x04,
    CellUnderTempWhileDischarging = 0x05,
    DischargeFetOverTempWhileDischarging = 0x06,
    NotUsed0x07 = 0x07,
    CellOverVoltageWhileCharging = 0x08,
    CellUnderVoltageWhileDischarging = 0x09,
    CellVoltageTooLow = 0x0a,
    SevereCellUnbalance = 0x0b,
    NotUsed0x0c = 0x0c,
    PackOverVoltage = 0x0d,
    NotUsed0x0e = 0x0e,
    VoltageSumDifference = 0x0f,
    ModuleUnderVoltage = 0x10,
    NotUsed0x11 = 0x11,
    NotUsed0x12 = 0x12,
    NotUsed0x13 = 0x13,
    NotUsed0x14 = 0x14,
    ShortCircuitWhileCharging = 0x15,
    OverCurrent65AWhileCharging = 0x16,
    OverCurrent85AWhileCharging = 0x17,
    NotUsed0x18 = 0x18,
    ShortCircuitWhileDischarging = 0x19,
    OverCurrent65AWhileDischarging = 0x1a,
    OverCurrent85AWhileDischarging = 0x1b,
    OverCurrentWhileDischarging = 0x1c,
    CurrentMeasurementError = 0x1d,
    NotUsed0x1e = 0x1e,
    NotUsed0x1f = 0x1f,
    NotUsed0x20 = 0x20,
    NotUsed0x21 = 0x21,
    NotUsed0x22 = 0x22,
    NotUsed0x23 = 0x23,
    NotUsed0x24 = 0x24,
    NotUsed0x25 = 0x25,
    NotUsed0x26 = 0x26,
    NotUsed0x27 = 0x27,
    NotUsed0x28 = 0x28,
    AdcMinScale = 0x29,
    AdcMaxScale = 0x2a,
    CellTempSensorHighFailure = 0x2b,
    CellTempSensorLowFailure = 0x2c,
    FetTempSensorHighFailure = 0x2d,
    FetTempSensorLowFailure = 0x2e,
    NotUsed0x2f = 0x2f,
    NotUsed0x30 = 0x30,
    NotUsed0x31 = 0x31,
    CurrentSensorHighFailure = 0x32,
    NotUsed0x33 = 0x33,
    CurrentSensorHighFailureWhileDischarging = 0x34,
    DischargeFetShorted = 0x35,
    ChargeFetShorted = 0x36,
    NotUsed0x37 = 0x37,
    TempDischargeErrorLock = 0x38,
    TempChargeErrorLock = 0x39,
    OverCurrentWhileRecuperating = 0x3a,
    CellOverVoltageWhileRecuperating = 0x3b,
    V24UnderVoltage = 0x3c,
    V24OverVoltage = 0x3d,
    CanNodeIdNotAssigned = 0x3e,
    CanNodeIdDuplicate = 0x3f,
    ParameterConfigError = 0x40,
    AnalogFrontEndCommunicationErorr = 0x41,
    AnalogFrontEndSelftestError = 0x42,
    AnalogFrontEndFullScaleError = 0x43,
    TempMuxSelftestError = 0x44,

    Unknown = 0xff,
}
