[package]
name = "varta-easyblade"
version = "0.1.0"
edition = "2024"

[features]
std = []
default = [ "std" ]

[build-dependencies]
anyhow = "1.0.103"
dbc-codegen = { git = "https://github.com/oxibus/dbc-codegen.git" }

[dependencies]
bitvec = "1.0.1"
embedded-can = "0.4.1"
num_enum = "0.7.6"
socketcan = { version = "3.6.2", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.27", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1.45.0", features = ["rt", "sync"] }
zencan-client = { git = "https://github.com/mcbridejc/zencan.git", rev="c8eb8f44548cd5515496fa0e385083a839674c14", features = ["socketcan"] }
